import re

with open('src/pages/JobsPage.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

# Locate the block by byte positions found earlier
start_idx = 14962
end_idx = content.find('      {/* Sub-tasks */')

print(f"start={start_idx} end={end_idx}")

new_block = (
    '        {/* Employee: actions gated behind check-in */}\n'
    '        {isEmployee && (\n'
    '          <div className="flex gap-2 mt-3 flex-wrap">\n'
    '\n'
    '            {/* Not checked in yet */}\n'
    '            {!checkedIn && job.status !== "completed" && (\n'
    '              <button onClick={() => onOpenCheckIn?.(job)}\n'
    '                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all"\n'
    '                style={{ background: "rgba(76,122,45,0.15)", border: "1px solid rgba(76,122,45,0.35)", color: "#6DBF4A" }}\n'
    '                onMouseEnter={e => e.currentTarget.style.boxShadow = "0 0 14px rgba(76,122,45,0.45)"}\n'
    '                onMouseLeave={e => e.currentTarget.style.boxShadow = "none"}>\n'
    '                <MapPin className="w-3 h-3" /> Check In\n'
    '              </button>\n'
    '            )}\n'
    '\n'
    '            {/* Checked in badge + unlocked work */}\n'
    '            {checkedIn && job.status !== "completed" && (\n'
    '              <>\n'
    '                <span className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold"\n'
    '                  style={{ background: "rgba(76,122,45,0.12)", border: "1px solid rgba(76,122,45,0.3)", color: "#6DBF4A" }}>\n'
    '                  <CheckCircle2 className="w-3 h-3" />\n'
    '                  Checked In\n'
    '                  {checkInTime && (\n'
    '                    <span className="ml-1 font-normal" style={{ opacity: 0.6 }}>\n'
    '                      {new Date(checkInTime).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}\n'
    '                    </span>\n'
    '                  )}\n'
    '                </span>\n'
    '                {completedCount > 0 ? (\n'
    '                  <>\n'
    '                    {!job.reportImage && !job.reportAudio && !job.reportNote ? (\n'
    '                      <button onClick={() => onOpenReport?.(job)}\n'
    '                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-emerald-50 border border-emerald-200 text-xs font-semibold text-emerald-700 hover:bg-emerald-100 transition-colors">\n'
    '                        <FileText className="w-3 h-3" /> Add Report\n'
    '                      </button>\n'
    '                    ) : (\n'
    '                      <button onClick={() => onOpenReport?.(job)}\n'
    '                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-blue-50 border border-blue-200 text-xs font-semibold text-blue-700 hover:bg-blue-100 transition-colors">\n'
    '                        <FileText className="w-3 h-3" /> View Report\n'
    '                      </button>\n'
    '                    )}\n'
    '                    <button onClick={() => onOpenVideoReport?.(job)}\n'
    '                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all"\n'
    '                      style={{ background: "rgba(76,122,45,0.15)", border: "1px solid rgba(76,122,45,0.3)", color: "#6DBF4A" }}\n'
    '                      onMouseEnter={e => e.currentTarget.style.boxShadow = "0 0 16px rgba(76,122,45,0.5)"}\n'
    '                      onMouseLeave={e => e.currentTarget.style.boxShadow = "none"}>\n'
    '                      <Video className="w-3 h-3" /> Video Report\n'
    '                    </button>\n'
    '                    {completedCount < jobSubJobs.length && (\n'
    '                      <span className="flex items-center px-2 py-1 rounded-xl text-[10px] font-semibold"\n'
    '                        style={{ background: "rgba(228,87,46,0.12)", color: "#E4572E", border: "1px solid rgba(228,87,46,0.2)" }}>\n'
    '                        {completedCount}/{jobSubJobs.length} tasks done\n'
    '                      </span>\n'
    '                    )}\n'
    '                  </>\n'
    '                ) : (\n'
    '                  <span className="flex items-center px-2 py-1 rounded-xl text-[10px] font-semibold"\n'
    '                    style={{ background: "rgba(76,122,45,0.08)", color: "rgba(109,191,74,0.7)", border: "1px solid rgba(76,122,45,0.15)" }}>\n'
    '                    Expand tasks below to start\n'
    '                  </span>\n'
    '                )}\n'
    '              </>\n'
    '            )}\n'
    '\n'
    '            {/* Completed job */}\n'
    '            {job.status === "completed" && (\n'
    '              <>\n'
    '                {!job.reportImage && !job.reportAudio && !job.reportNote ? (\n'
    '                  <button onClick={() => onOpenReport?.(job)}\n'
    '                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-emerald-50 border border-emerald-200 text-xs font-semibold text-emerald-700 hover:bg-emerald-100 transition-colors">\n'
    '                    <FileText className="w-3 h-3" /> Add Report\n'
    '                  </button>\n'
    '                ) : (\n'
    '                  <button onClick={() => onOpenReport?.(job)}\n'
    '                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-blue-50 border border-blue-200 text-xs font-semibold text-blue-700 hover:bg-blue-100 transition-colors">\n'
    '                    <FileText className="w-3 h-3" /> View Report\n'
    '                  </button>\n'
    '                )}\n'
    '                <button onClick={() => onOpenVideoReport?.(job)}\n'
    '                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all"\n'
    '                  style={{ background: "rgba(76,122,45,0.15)", border: "1px solid rgba(76,122,45,0.3)", color: "#6DBF4A" }}\n'
    '                  onMouseEnter={e => e.currentTarget.style.boxShadow = "0 0 16px rgba(76,122,45,0.5)"}\n'
    '                  onMouseLeave={e => e.currentTarget.style.boxShadow = "none"}>\n'
    '                  <Video className="w-3 h-3" /> Video Report\n'
    '                </button>\n'
    '              </>\n'
    '            )}\n'
    '\n'
    '          </div>\n'
    '        )}\n'
    '      </div>\n'
    '\n'
)

new_content = content[:start_idx] + new_block + content[end_idx:]

with open('src/pages/JobsPage.jsx', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('Done. File length:', len(new_content))
